language: node_js
before_install:
- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
- travis_retry gem install bitballoon
install:
- yarn install
cache:
  directories:
  - $HOME/.yarn-cache
node_js:
- '5'
script:
- npm run build
after_success:
- bitballoon deploy dist --access-token=$BB_ACCESS_TOKEN --site-id=$BB_SITE_ID
branches:
  only:
  - master
env:
  global:
  - secure: N2cLtlmvsfAUuRRKp0i1VCHzzxEquEQaDflQ3z5bPMGE9CY1+rmCLmTV4jEXesAOIzviSepMukFg3eA0m1i/fA7SlY+1sgaJhSS5Uu1jhvjMl1o+ee/FBS+aE1q6BgupkOPqOsLnV5lw4FXpWtwYpMl/uZvrhwX/i7w1Q7RTJPTrbWdz6Ftct5RoBImrnfG1pdpso4EFSl/X00bv8/+d2HQgVcW98/SbQgtXxDr4qGqcJa353+bgMiEzSJdwKX6wQEm/qNYjyp8zZLVvE6KXuiaQSkoOC0vAaorT93kz0qohzk8coX14Z/FyfMtqgXjbhbg73kPAEgFiiFMU1vIzlJQ1Rm/pWMaZT9ltDbAxv7vjF1LMR/YTke2k0mmgx6hPPev9MdfNwLQB6DcUGPX7vKUleXw+a1h1xSGRZ6UfD0zNKoF+JnFuhCzaSadlNdHemXyAHubppe7qPBP2ApmPWHAAye/MEXPjuSGB/wVVpEY0Lu8QQh8eRKm5Wy9QifqM3e/87Mbc4IlTrS8emfLspfNaXqBOOYh4ZoA3EPPw5Onihw5wqmYTkuwpN0zE91h1IdeRDxySWuRaLkudRsWsBHcUF70mVnt+lnA3dZFgGoD7GuBTd+HlX7Cp5lLR2ml0Yqnpv8EIfkV+Bg+AuMI1tGHvRCTVic/QivYXXh3/q7A=
  - secure: hPSOsNBn4fhep4TTahfm2ysc0b+rIdYXJq3N6N6XzASa77uEtB29vvk6Ned53xI/6swEcEgdbNC6K0klV0Lz3JtVcj4g8vOmGX63MjkadLFDx4MmLdI0Ogy0Fp51WJ0uW8/xSlXnbO7m8ASsfDRts5FdNzk/uVlnpZXbMIbimIABVwd3zD/O0vfwkrb4K9Bj5UtnHQomD1sXGik7C3X/LdxAPIM8l441F7LOwvWD/w+Sryg5CoyEDdDW0fPUs41DyPDQL7g0nDuQyc36OCVkpyX4I0y2leIyWGSVfbvvdt6AOGw2hqPNA2KNYrLRQ9pUJB/QQlz4Am7oxq/nHSiMsT2TS76O27cAMyyctjvI9mMYQ4E5NDoJN9Hp6yywxcTv1wV9GVofQ8t+wDE1TLIV1h/JqoVpWAfeNvwUiOortN3M0/L2m5b8RMJ6UljNr+WarMOd7gDE3ysVsVrzwAnP3wEKcEDmgp+/qALDET4rip3DMbQF/Bv9kqwyn+MO/SyUBp4wLJvN8GoHL4DSKVozle7f8nacspLsGCXCR5+qdVXQcEXS89KbMQGSYtVkBCO7Me5aH/YmFtuKdV1FFnH5m+ZdnpY686qrzHTdZKjTHlickNCso/a6gCAbyE9RWGti5x5bh8/h/+r920x7qENqETewSejy0jMu7g5qE5PyqA0=
